[nvim] update packages

diff --git a/config/local/.local/bin/keygen b/config/local/.local/bin/keygen
--- a/config/local/.local/bin/keygen
+++ b/config/local/.local/bin/keygen
@@ -87,10 +87,10 @@ function keygen(){
         echo -e "Key '$KEY' created in '$KEYS/'...\n"
 
         if [ "$INPUT" -eq 2 ]; then 
-          # create PEM file for rsa keys
-          PEM="$KEYS/$KEY.pub.pem"
-          ssh-keygen -f "$KEYS/$KEY.pub" -m pem -e >> "$PEM"
-          [[ $? -ne 0 ]] && echo "Could not generate PEM file" 1>&2 && rm "$PEM" || echo "Generated PEM file: $PEM"
+            # create PEM file for rsa keys
+            PEM="$KEYS/$KEY.pub.pem"
+            ssh-keygen -f "$KEYS/$KEY.pub" -m pem -e >> "$PEM"
+            [[ $? -ne 0 ]] && echo "Could not generate PEM file" 1>&2 && rm "$PEM" || echo "Generated PEM file: $PEM"
         fi
 
         # add to authorized keys
